# Generated by Django 2.0.5 on 2018-06-12 06:00

import RipoffServer.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rda_discount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='RDA Discount')),
                ('cc_discount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Cougar Cash Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('discount_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RipoffServer.DiscountPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ripoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=40)),
                ('payment_type', models.CharField(choices=[(RipoffServer.models.PaymentType('Credit Card'), 'Credit Card'), (RipoffServer.models.PaymentType('Cougar Cash'), 'Cougar Cash'), (RipoffServer.models.PaymentType('RDA'), 'RDA')], max_length=3)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.ForeignKey(on_delete=None, to='RipoffServer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rda_plan', models.IntegerField(verbose_name='RDA Plan')),
                ('wsu_id', models.CharField(max_length=8, verbose_name='WSU ID Number')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ripoff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RipoffServer.SiteUser'),
        ),
    ]
