# Generated by Django 2.0.5 on 2018-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountplan',
            name='name',
            field=models.CharField(default='hello', max_length=40),
            preserve_default=False,
        ),
    ]
