# Generated by Django 2.0.5 on 2018-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0002_discountplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripoff',
            name='amount',
        ),
        migrations.AddField(
            model_name='ripoff',
            name='ripoff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
