# Generated by Django 2.0.5 on 2018-07-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0003_auto_20180713_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripoff',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RipoffServer.Location'),
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RipoffServer.Product'),
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RipoffServer.SiteUser'),
            preserve_default=False,
        ),
    ]
