# Generated by Django 2.0.5 on 2018-07-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0005_auto_20180713_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripoff',
            name='ripoff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
