# Generated by Django 2.0.5 on 2018-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0006_auto_20180713_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripoff',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='payment_type',
            field=models.CharField(choices=[('CRD', 'Credit Card'), ('CGR', 'Cougar Cash'), ('RDA', 'RDA')], max_length=3),
        ),
    ]
