# Generated by Django 2.0.5 on 2018-07-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0007_auto_20180713_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDAPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(max_length=1, verbose_name='Plan Number')),
                ('base_cost', models.IntegerField(max_length=4, verbose_name='Plan Base Cost')),
                ('dollars', models.IntegerField(max_length=4, verbose_name='RDA Dollars')),
            ],
        ),
        migrations.RenameField(
            model_name='discountplan',
            old_name='cc_discount',
            new_name='cgr_discount',
        ),
        migrations.RenameField(
            model_name='ripoff',
            old_name='base_cost',
            new_name='base_price',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='rda_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RipoffServer.RDAPlan', verbose_name='RDA Plan'),
        ),
    ]
