# Generated by Django 2.0.5 on 2018-11-30 20:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('RipoffServer', '0009_auto_20180718_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdaplan',
            options={'verbose_name': 'RDA Plan', 'verbose_name_plural': 'RDA Plans'},
        ),
        migrations.AlterModelManagers(
            name='discountplan',
            managers=[
                ('plans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('locations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rdaplan',
            managers=[
                ('plans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ripoff',
            managers=[
                ('ripoffs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('users', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='discount_plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='RipoffServer.DiscountPlan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ripoffs', to='RipoffServer.Location'),
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ripoffs', to='RipoffServer.Product'),
        ),
        migrations.AlterField(
            model_name='ripoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ripoffs', to='RipoffServer.SiteUser'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='rda_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='RipoffServer.RDAPlan', verbose_name='RDA Plan'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='wsu_id',
            field=models.CharField(max_length=8, verbose_name='WSU ID #'),
        ),
    ]
